[evals]
trials = 20
targets = [
  { provider = "ollama", model = "llama3.2:1b" },
  { provider = "ollama", model = "llama3.2:3b" },
  { provider = "ollama", model = "llama3.3:70b" },
  { provider = "ollama", model = "qwen3.5:35b-a3b" },
  { provider = "ollama", model = "mistral-nemo" },
  # { provider = "openai", model = "gpt-5.3-codex" },
  # { provider = "openrouter", model = "google/gemini-3-flash" },
]

[provider.ollama]
url = "http://192.168.0.2:11434"
